//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// Ce code source a été automatiquement généré par wsdl, Version=4.6.81.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="ClientServicesSoap", Namespace="http://tempuri.org/")]
public partial class ClientServices : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback CreateProfilOperationCompleted;
    
    private System.Threading.SendOrPostCallback GetProfilOperationCompleted;
    
    private System.Threading.SendOrPostCallback UpdateGroupSignOperationCompleted;
    
    private System.Threading.SendOrPostCallback GetEventGameOperationCompleted;
    
    /// <remarks/>
    public ClientServices() {
        this.Url = "http://localhost:9090/ClientServices.asmx";
    }
    
    /// <remarks/>
    public event CreateProfilCompletedEventHandler CreateProfilCompleted;
    
    /// <remarks/>
    public event GetProfilCompletedEventHandler GetProfilCompleted;
    
    /// <remarks/>
    public event UpdateGroupSignCompletedEventHandler UpdateGroupSignCompleted;
    
    /// <remarks/>
    public event GetEventGameCompletedEventHandler GetEventGameCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreateProfil", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public ProfilS CreateProfil(string name, string tokenId) {
        object[] results = this.Invoke("CreateProfil", new object[] {
                    name,
                    tokenId});
        return ((ProfilS)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginCreateProfil(string name, string tokenId, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("CreateProfil", new object[] {
                    name,
                    tokenId}, callback, asyncState);
    }
    
    /// <remarks/>
    public ProfilS EndCreateProfil(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((ProfilS)(results[0]));
    }
    
    /// <remarks/>
    public void CreateProfilAsync(string name, string tokenId) {
        this.CreateProfilAsync(name, tokenId, null);
    }
    
    /// <remarks/>
    public void CreateProfilAsync(string name, string tokenId, object userState) {
        if ((this.CreateProfilOperationCompleted == null)) {
            this.CreateProfilOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateProfilOperationCompleted);
        }
        this.InvokeAsync("CreateProfil", new object[] {
                    name,
                    tokenId}, this.CreateProfilOperationCompleted, userState);
    }
    
    private void OnCreateProfilOperationCompleted(object arg) {
        if ((this.CreateProfilCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.CreateProfilCompleted(this, new CreateProfilCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetProfil", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public ProfilS GetProfil(string name, string tokenId) {
        object[] results = this.Invoke("GetProfil", new object[] {
                    name,
                    tokenId});
        return ((ProfilS)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetProfil(string name, string tokenId, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetProfil", new object[] {
                    name,
                    tokenId}, callback, asyncState);
    }
    
    /// <remarks/>
    public ProfilS EndGetProfil(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((ProfilS)(results[0]));
    }
    
    /// <remarks/>
    public void GetProfilAsync(string name, string tokenId) {
        this.GetProfilAsync(name, tokenId, null);
    }
    
    /// <remarks/>
    public void GetProfilAsync(string name, string tokenId, object userState) {
        if ((this.GetProfilOperationCompleted == null)) {
            this.GetProfilOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetProfilOperationCompleted);
        }
        this.InvokeAsync("GetProfil", new object[] {
                    name,
                    tokenId}, this.GetProfilOperationCompleted, userState);
    }
    
    private void OnGetProfilOperationCompleted(object arg) {
        if ((this.GetProfilCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetProfilCompleted(this, new GetProfilCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateGroupSign", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public bool UpdateGroupSign(int eventId, int profilId, int score) {
        object[] results = this.Invoke("UpdateGroupSign", new object[] {
                    eventId,
                    profilId,
                    score});
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginUpdateGroupSign(int eventId, int profilId, int score, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("UpdateGroupSign", new object[] {
                    eventId,
                    profilId,
                    score}, callback, asyncState);
    }
    
    /// <remarks/>
    public bool EndUpdateGroupSign(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public void UpdateGroupSignAsync(int eventId, int profilId, int score) {
        this.UpdateGroupSignAsync(eventId, profilId, score, null);
    }
    
    /// <remarks/>
    public void UpdateGroupSignAsync(int eventId, int profilId, int score, object userState) {
        if ((this.UpdateGroupSignOperationCompleted == null)) {
            this.UpdateGroupSignOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateGroupSignOperationCompleted);
        }
        this.InvokeAsync("UpdateGroupSign", new object[] {
                    eventId,
                    profilId,
                    score}, this.UpdateGroupSignOperationCompleted, userState);
    }
    
    private void OnUpdateGroupSignOperationCompleted(object arg) {
        if ((this.UpdateGroupSignCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.UpdateGroupSignCompleted(this, new UpdateGroupSignCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetEventGame", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public EventGame GetEventGame() {
        object[] results = this.Invoke("GetEventGame", new object[0]);
        return ((EventGame)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetEventGame(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetEventGame", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public EventGame EndGetEventGame(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((EventGame)(results[0]));
    }
    
    /// <remarks/>
    public void GetEventGameAsync() {
        this.GetEventGameAsync(null);
    }
    
    /// <remarks/>
    public void GetEventGameAsync(object userState) {
        if ((this.GetEventGameOperationCompleted == null)) {
            this.GetEventGameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetEventGameOperationCompleted);
        }
        this.InvokeAsync("GetEventGame", new object[0], this.GetEventGameOperationCompleted, userState);
    }
    
    private void OnGetEventGameOperationCompleted(object arg) {
        if ((this.GetEventGameCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetEventGameCompleted(this, new GetEventGameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
public partial class ProfilS {
    
    private int idField;
    
    private string nameField;
    
    private string avatarField;
    
    private int rankField;
    
    private string tokenidField;
    
    /// <remarks/>
    public int id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string avatar {
        get {
            return this.avatarField;
        }
        set {
            this.avatarField = value;
        }
    }
    
    /// <remarks/>
    public int rank {
        get {
            return this.rankField;
        }
        set {
            this.rankField = value;
        }
    }
    
    /// <remarks/>
    public string tokenid {
        get {
            return this.tokenidField;
        }
        set {
            this.tokenidField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
public partial class PriceS {
    
    private int idField;
    
    private string nameField;
    
    private string descriptionField;
    
    private byte[] imageField;
    
    private byte[] pathField;
    
    /// <remarks/>
    public int id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
    public byte[] image {
        get {
            return this.imageField;
        }
        set {
            this.imageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
    public byte[] path {
        get {
            return this.pathField;
        }
        set {
            this.pathField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
public partial class PricePoolS {
    
    private int idField;
    
    private int eventIdField;
    
    private int priceIdField;
    
    private float placePercentField;
    
    private int placeRangeMinField;
    
    private int placeRangeMaxField;
    
    /// <remarks/>
    public int id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public int eventId {
        get {
            return this.eventIdField;
        }
        set {
            this.eventIdField = value;
        }
    }
    
    /// <remarks/>
    public int priceId {
        get {
            return this.priceIdField;
        }
        set {
            this.priceIdField = value;
        }
    }
    
    /// <remarks/>
    public float placePercent {
        get {
            return this.placePercentField;
        }
        set {
            this.placePercentField = value;
        }
    }
    
    /// <remarks/>
    public int placeRangeMin {
        get {
            return this.placeRangeMinField;
        }
        set {
            this.placeRangeMinField = value;
        }
    }
    
    /// <remarks/>
    public int placeRangeMax {
        get {
            return this.placeRangeMaxField;
        }
        set {
            this.placeRangeMaxField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
public partial class EventS {
    
    private int idField;
    
    private string nameField;
    
    private byte[] imageField;
    
    private string descriptionField;
    
    private System.DateTime startDateField;
    
    private System.DateTime endDateField;
    
    /// <remarks/>
    public int id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
    public byte[] image {
        get {
            return this.imageField;
        }
        set {
            this.imageField = value;
        }
    }
    
    /// <remarks/>
    public string description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime startDate {
        get {
            return this.startDateField;
        }
        set {
            this.startDateField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime endDate {
        get {
            return this.endDateField;
        }
        set {
            this.endDateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
public partial class EventGame {
    
    private EventS eventSField;
    
    private PricePoolS[] pricepoolsField;
    
    private PriceS[] pricesField;
    
    /// <remarks/>
    public EventS eventS {
        get {
            return this.eventSField;
        }
        set {
            this.eventSField = value;
        }
    }
    
    /// <remarks/>
    public PricePoolS[] pricepools {
        get {
            return this.pricepoolsField;
        }
        set {
            this.pricepoolsField = value;
        }
    }
    
    /// <remarks/>
    public PriceS[] prices {
        get {
            return this.pricesField;
        }
        set {
            this.pricesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
public delegate void CreateProfilCompletedEventHandler(object sender, CreateProfilCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class CreateProfilCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal CreateProfilCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public ProfilS Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((ProfilS)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
public delegate void GetProfilCompletedEventHandler(object sender, GetProfilCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetProfilCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetProfilCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public ProfilS Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((ProfilS)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
public delegate void UpdateGroupSignCompletedEventHandler(object sender, UpdateGroupSignCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class UpdateGroupSignCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal UpdateGroupSignCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public bool Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((bool)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
public delegate void GetEventGameCompletedEventHandler(object sender, GetEventGameCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.81.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetEventGameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetEventGameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public EventGame Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((EventGame)(this.results[0]));
        }
    }
}
